<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hal" nsURI="https://www.mcgill.ca/emf/examples/hal" nsPrefix="hal">
  <eClassifiers xsi:type="ecore:EClass" name="HALSystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="homeAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//AutomationRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activitylog" lowerBound="1"
        eType="#//ActivityLog" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="readings" upperBound="-1"
        eType="#//SensorReading" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" upperBound="-1"
        eType="#//IssuedCommand" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" upperBound="-1"
        eType="#//Room" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensors" upperBound="-1"
        eType="#//Sensor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuators" upperBound="-1"
        eType="#//Actuator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensors" upperBound="-1"
        eType="#//Sensor" eOpposite="#//Sensor/room"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuators" upperBound="-1"
        eType="#//Actuator" eOpposite="#//Actuator/room"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" lowerBound="1" eType="#//Room"
        eOpposite="#//Room/sensors"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="readings" upperBound="-1"
        eType="#//SensorReading" eOpposite="#//SensorReading/sensor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SensorType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actuator" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" lowerBound="1" eType="#//Room"
        eOpposite="#//Room/actuators"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="possibleCommands" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" upperBound="-1"
        eType="#//IssuedCommand" eOpposite="#//IssuedCommand/actuator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//ActuatorType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorReading">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activitylog" lowerBound="1"
        eType="#//ActivityLog" eOpposite="#//ActivityLog/readings"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" eType="#//Sensor"
        eOpposite="#//Sensor/readings"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IssuedCommand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activitylog" lowerBound="1"
        eType="#//ActivityLog" eOpposite="#//ActivityLog/commands"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="command" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuator" eType="#//Actuator"
        eOpposite="#//Actuator/commands"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityLog">
    <eStructuralFeatures xsi:type="ecore:EReference" name="readings" eType="#//SensorReading"
        eOpposite="#//SensorReading/activitylog"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" upperBound="-1"
        eType="#//IssuedCommand" eOpposite="#//IssuedCommand/activitylog"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//AutomationRule" eOpposite="#//AutomationRule/activitylog"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutomationRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activitylog" lowerBound="1"
        eType="#//ActivityLog" eOpposite="#//ActivityLog/rules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SensorType">
    <eLiterals name="Temperature" literal="Temperature"/>
    <eLiterals name="Movement" value="1" literal="Movement"/>
    <eLiterals name="Light" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActuatorType">
    <eLiterals name="Heater" literal="Heater"/>
    <eLiterals name="Lock" value="1" literal="Lock"/>
    <eLiterals name="LightSwitch" value="2" literal="LightSwitch"/>
  </eClassifiers>
</ecore:EPackage>
